trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  solution: '**/*.sln'

steps:
- script: dotnet build $(solution) --configuration $(buildConfiguration)
  displayName: 'Build Solution'